networks:
  apps:
volumes:
  crispypod-files:

services:
  frontend:
    image: ghcr.io/crispypod/frontend:latest
    container_name: frontend
    hostname: frontend
    ports:
      - 3000:3000
    environment:
      - PUBLIC_PB_ENDPOINT=http://backend:8080
    networks:
      - apps
    depends_on:
      - backend

  backend:
    image: ghcr.io/crispypod/backend:latest
    container_name: backend
    hostname: backend
    environment:
      - DISABLE_PB_WEBUI=1
    networks:
      - apps
    volumes:
      - crispypod-files:/crispypod/pb_data

    