volumes:
  crispypod-files:

services:
  app:
    image: ghcr.io/crispypod/crispypod:latest
    container_name: app
    hostname: app
    environment:
      - PUBLIC_PB_ENDPOINT=http://localhost:8080
    ports:
      - 3000:3000
    volumes:
      - crispypod-files:/crispypod/pb_data

    