// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Credential struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type Episode struct {
	ID                  string  `json:"id"`
	Title               string  `json:"title"`
	CreateTime          int     `json:"createTime"`
	Description         string  `json:"description"`
	PublishTime         *int    `json:"publishTime,omitempty"`
	ThumbnailFileName   *string `json:"thumbnailFileName,omitempty"`
	ThumbnailUploadName *string `json:"thumbnailUploadName,omitempty"`
	AudioFileName       *string `json:"audioFileName,omitempty"`
	AudioFileUploadName *string `json:"audioFileUploadName,omitempty"`
	AudioFileDuration   *string `json:"audioFileDuration,omitempty"`
	User                *User   `json:"user"`
}

type LoginData struct {
	Token string `json:"token"`
}

type NewEpisode struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
}

type Pagination struct {
	PageIndex *int `json:"pageIndex,omitempty"`
	PerPage   *int `json:"perPage,omitempty"`
}

type SiteConfig struct {
	ID              string `json:"id"`
	SiteName        string `json:"siteName"`
	SiteDescription string `json:"siteDescription"`
	SiteURL         string `json:"siteUrl"`
}

type User struct {
	ID          string `json:"id"`
	CreateTime  int    `json:"createTime"`
	Email       string `json:"email"`
	UserName    string `json:"userName"`
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`
}
